# .github/workflows/publish.yml

name: Publish Package

# Event for the workflow
on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@hundo-careers/hundo-design-system'
      - name: Install Dependencies
        run: |
          echo "@hundo-careers:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_PAT" >> .npmrc
          npm install
        env:
          GITHUB_PAT: ${{ secrets.REPO_READ_PAT }}
      - name: Build & Release  
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
